// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpPoXYyRnNFb2oan_HEsPJvECY3bAl1QA',
    appId: '1:172506945207:web:3d68653a4087c341081f32',
    messagingSenderId: '172506945207',
    projectId: 'calorie-tracker-74ec7',
    authDomain: 'calorie-tracker-74ec7.firebaseapp.com',
    storageBucket: 'calorie-tracker-74ec7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezbN3ZT7oC8dJPeAgdBGYZk_XCPqOaic',
    appId: '1:172506945207:android:7494edf497602c5f081f32',
    messagingSenderId: '172506945207',
    projectId: 'calorie-tracker-74ec7',
    storageBucket: 'calorie-tracker-74ec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxi6q4avLJF2tGr2IKq-jCd2SwHXYMOn0',
    appId: '1:172506945207:ios:0ca95585ca540491081f32',
    messagingSenderId: '172506945207',
    projectId: 'calorie-tracker-74ec7',
    storageBucket: 'calorie-tracker-74ec7.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpPoXYyRnNFb2oan_HEsPJvECY3bAl1QA',
    appId: '1:172506945207:web:515e2d6a6f3c26b5081f32',
    messagingSenderId: '172506945207',
    projectId: 'calorie-tracker-74ec7',
    authDomain: 'calorie-tracker-74ec7.firebaseapp.com',
    storageBucket: 'calorie-tracker-74ec7.firebasestorage.app',
  );
}
